\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {lstlisting}{\numberline {3.1}Code-Beispiel}{6}{lstlisting.3.1}%
\contentsline {lstlisting}{\numberline {3.2}Python-Code}{6}{lstlisting.3.2}%
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
